apimServiceName: apim-prod-hs0220
apis:
  - name: star-wars-api
    properties:
      authenticationSettings: {}
namedValues:
  - name: environment
    properties:
      displayName: environment
      value: "https://www.search2.com"
